services:
  bve:
    build:
      dockerfile_inline: |
        FROM rust:1-slim
        RUN apt-get update && \
          apt-get -y install libpq-dev && \
          cargo install cargo-watch && \
          cargo install diesel_cli --no-default-features --features postgres
    working_dir: /usr/src/myapp
    volumes:
      - ./backend-ve:/usr/src/myapp
    command: cargo watch -x run
    environment:
      - DATABASE_URL=postgres://postgres:sergtsop@db/ve
    depends_on:
      - db
    expose:
      - 3000
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.bve.rule=Host(`ve.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.bve.tls=true"
  fve:
    build:
      context: frontend-ve
      target: base
    volumes:
      - ./frontend-ve:/usr/src/app
    command: dev
    networks:
      - docker_default
      - default
    environment:
      - HOST=ve.localhost
    labels:
      - "traefik.http.routers.fve.rule=Host(`ve.localhost`)"
      - "traefik.http.routers.fve.tls=true"
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sergtsop
      - POSTGRES_DB=ve

networks:
  docker_default:
    external: true
    name: docker_default
