version: '3.9'
services:
  bve:
    build:
      dockerfile_inline: |
        FROM rust:1-slim
        RUN apt-get update && \
          apt-get -y install libssl-dev pkg-config && \
          cargo install cargo-watch sqlx-cli
    working_dir: /usr/src/myapp
    volumes:
      - ./backend-ve:/usr/src/myapp
    command: cargo watch -x run
    depends_on:
      - db
    expose:
      - 3000
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.bve.rule=Host(`ve.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.bve.tls=true"
  fve:
    build:
      dockerfile_inline: |
        FROM rust:1-slim
        RUN rustup target add wasm32-unknown-unknown \
           && cargo install trunk && apt-get update\
           && apt-get -y install curl \
           && curl -sLo /usr/local/bin/tailwind https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.3/tailwindcss-linux-x64 \
           && chmod +x /usr/local/bin/tailwind
    working_dir: /usr/src/myapp
    volumes:
      - ./frontend-ve:/usr/src/myapp
    command: trunk serve
    expose:
      - 8080
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.fve.rule=Host(`ve.localhost`)"
      - "traefik.http.routers.fve.tls=true"
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sergtsop
      - POSTGRES_DB=ve

networks:
  docker_default:
    external: true
    name: docker_default
