import type { Metadata } from "next";
import { BIZ_UDPGothic, Inter } from "next/font/google";
import "./globals.css";

const ud = BIZ_UDPGothic({
  weight: ["400", "700"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ud.className}>{children}</body>
    </html>
  );
}
